### ISSUE TITLE
Help is currently broken

### ISSUE THREAD

**Issue by HenrickTheBull** [HenrickTheBull/TKH4SH#3]
**Describe the bug**
Help is not displaying, there is currently an issue with the language module?

**To Reproduce**
1. Go to H4SH's DMs and type '/help'

**Expected behavior**
Help should display.

**Additional context**
```py
An exception was raised while handling an update
User: 950625922
Chat: None 950625922
Callback data: None
Message: /help

Full Traceback: Traceback (most recent call last):
  File "/home/ubuntu/TavernKeeper/tg_bot/langs/language.py", line 13, in get_string
    return self.languages[lang][string]
KeyError: 'en'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/ext/utils/promise.py", line 79, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/home/ubuntu/TavernKeeper/tg_bot/__main__.py", line 381, in get_help
    send_help(chat.id, (gs(chat.id, "pm_help_text")))
  File "/home/ubuntu/TavernKeeper/tg_bot/modules/language.py", line 30, in gs
    return get_string(lang, string)
  File "/home/ubuntu/TavernKeeper/tg_bot/langs/language.py", line 16, in get_string
    en_string = self.languages["en"].get(string)
KeyError: 'en'```

**Comment by HenrickTheBull** [comment]
Fixed. I'm absolutely crazy.
